pipeline:
  name: Mr.Comic Testing Pipeline
  version: 1.0.0

stages:
  - build
  - static_analysis
  - unit_tests
  - ui_tests
  - report

build:
  stage: build
  script: ./pipeline/build-script.sh
  artifacts:
    paths:
      - build/
    expire_in: 1 week

static_analysis:
  stage: static_analysis
  script: ./pipeline/static-analysis.sh
  dependencies:
    - build
  artifacts:
    paths:
      - reports/static-analysis/
    expire_in: 1 week

unit_tests:
  stage: unit_tests
  script: ./pipeline/test-runner.sh --type=unit
  dependencies:
    - build
  artifacts:
    paths:
      - reports/unit-tests/
    expire_in: 1 week

ui_tests:
  stage: ui_tests
  script: ./pipeline/test-runner.sh --type=ui
  dependencies:
    - build
  artifacts:
    paths:
      - reports/ui-tests/
    expire_in: 1 week

report:
  stage: report
  script: ./pipeline/report-generator.sh
  dependencies:
    - static_analysis
    - unit_tests
    - ui_tests
  artifacts:
    paths:
      - reports/final/
    expire_in: 1 month
