[versions]
# Android
androidApplication = "8.7.0"
compileSdk = "34"
minSdk = "26"

# Kotlin
kotlinAndroid = "1.9.23"
ksp = "1.9.23-1.0.20"
kotlinCompilerExtension = "1.5.8"
jvmTarget = "17"

# AndroidX
composeBom = "2025.06.01"
lifecycle = "2.9.1"
navigation = "2.7.7"
room = "2.7.2"
datastore = "1.1.7"

# DI
hilt = "2.48"

# Testing
junit = "4.13.2"
kotlinxCoroutinesTest = "1.10.2"
mockitoCore = "5.18.0"
truth = "1.4.4"
mockitoKotlin = "5.4.0"

# Tooling
spotless = "6.25.0"
ktlintGradle = "11.6.1"

# Archives
zip4j = "2.11.5"
junrar = "7.5.5"
pdfiumAndroid = "1.9.2"
djvuAndroid = "1.0.0-beta.11"
telephoto = "0.13.0"

[libraries]
# AndroidX Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# AndroidX Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# AndroidX Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# AndroidX DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# DI - Hilt
google-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Testing
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
test-mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
test-truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
test-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }

# Archives
zip4j = { group = "net.lingala.zip4j", name = "zip4j", version.ref = "zip4j" }
junrar = { group = "com.github.junrar", name = "junrar", version.ref = "junrar" }

# PDF
pdfium-android = { group = "com.shockwave", name = "pdfium-android", version.ref = "pdfiumAndroid" }

# DJVU
djvu-android = { group = "com.github.Djvu-Android", name = "Djvu-Android", version.ref = "djvuAndroid" }

# Zoomable Image
telephoto-zoomable-image = { group = "me.saket.telephoto", name = "zoomable-image-compose", version.ref = "telephoto" }

[bundles]
compose = ["androidx-compose-ui", "androidx-compose-material3", "androidx-compose-ui-tooling-preview"]
room = ["androidx-room-runtime", "androidx-room-ktx"]
test-unit = ["test-junit", "test-kotlinx-coroutines", "test-mockito-core", "test-mockito-kotlin", "test-truth"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinAndroid" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }


