#!/bin/bash

echo "🔧 Исправление ошибок проекта MrComic..."

# Создание отсутствующих consumer-rules.pro файлов
echo "📝 Создание отсутствующих consumer-rules.pro файлов..."

modules=("core-analytics" "feature-themes" "core-domain")

for module in "${modules[@]}"; do
    if [ ! -f "android/$module/consumer-rules.pro" ]; then
        echo "# Consumer ProGuard rules for $module" > "android/$module/consumer-rules.pro"
        echo "# Add module-specific ProGuard rules here" >> "android/$module/consumer-rules.pro"
        echo "✅ Создан android/$module/consumer-rules.pro"
    fi
done

# Исправление Lint ошибок в build.gradle.kts файлах
echo "🔧 Исправление Lint ошибок..."

# Функция для добавления lint конфигурации в build.gradle.kts
add_lint_config() {
    local file="$1"
    if [ -f "$file" ]; then
        # Проверяем, есть ли уже lint конфигурация
        if ! grep -q "lint {" "$file"; then
            # Добавляем lint конфигурацию после android { блока
            sed -i '/android {/a\
    lint {\
        disable += "NullSafeMutableLiveData"\
    }' "$file"
            echo "✅ Добавлена lint конфигурация в $file"
        else
            echo "ℹ️  Lint конфигурация уже существует в $file"
        fi
    fi
}

# Добавляем lint конфигурацию во все модули
android_modules=("app" "core" "core-analytics" "core-data" "core-domain" "core-model" "core-reader" "core-ui" "feature-library" "feature-ocr" "feature-onboarding" "feature-reader" "feature-settings" "feature-themes" "shared")

for module in "${android_modules[@]}"; do
    build_file="android/$module/build.gradle.kts"
    if [ -f "$build_file" ]; then
        add_lint_config "$build_file"
    fi
done

# Исправление BookmarkEntity - добавление индекса
echo "🗄️  Исправление BookmarkEntity..."

bookmark_file="android/core-data/src/main/java/com/example/core/data/database/BookmarkEntity.kt"
if [ -f "$bookmark_file" ]; then
    # Добавляем импорт Index
    if ! grep -q "import androidx.room.Index" "$bookmark_file"; then
        sed -i '/import androidx.room.ForeignKey/a import androidx.room.Index' "$bookmark_file"
    fi
    
    # Добавляем индекс в Entity аннотацию
    if ! grep -q "indices = \[\[Index" "$bookmark_file"; then
        sed -i 's/foreignKeys = \[/foreignKeys = [\n    ],\n    indices = [\n        Index(value = ["comicId"])\n    ]/' "$bookmark_file"
        sed -i 's/],\n    indices = \[/,\n    indices = [/' "$bookmark_file"
    fi
    
    echo "✅ Исправлен BookmarkEntity с добавлением индекса"
fi

# Исправление устаревших Divider на HorizontalDivider
echo "🎨 Исправление устаревших Divider..."

# Файлы для исправления
divider_files=(
    "android/feature-settings/src/main/java/com/example/feature/settings/ui/SettingsScreen.kt"
    "android/feature-library/src/main/java/com/example/feature/library/ui/LibraryScreen.kt"
)

for file in "${divider_files[@]}"; do
    if [ -f "$file" ]; then
        # Заменяем Divider на HorizontalDivider
        sed -i 's/Divider(/HorizontalDivider(/g' "$file"
        echo "✅ Исправлен $file"
    fi
done

# Создание .gitignore для build директорий
echo "📁 Создание .gitignore..."

if [ ! -f ".gitignore" ]; then
    cat > .gitignore << EOF
# Built application files
*.apk
*.aar
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
#  Uncomment the following line in case you need and you don't have the release build type files in your app
# release/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizardSettings.xml
.idea/dictionaries
.idea/libraries
# Android Studio 3 in .gitignore file.
.idea/caches
.idea/modules.xml
# Comment next line if keeping position of elements in Navigation Editor is desired for your project
.idea/navEditor.xml

# Keystore files
# Uncomment the following lines if you do not want to check your keystore files in.
#*.jks
#*.keystore

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.cxx/

# Google Services (e.g. APIs or Firebase)
# google-services.json

# Freeline
freeline.py
freeline/
freeline_project_description.json

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output
fastlane/readme.md

# Version control
vcs.xml

# lint
lint/intermediates/
lint/generated/
lint/outputs/
lint/tmp/
# lint/reports/

# Android Profiling
*.hprof

# Detekt
reports/
EOF
    echo "✅ Создан .gitignore"
fi

echo "🎉 Исправление завершено!"
echo ""
echo "📋 Следующие шаги:"
echo "1. Запустите: ./gradlew clean"
echo "2. Запустите: ./gradlew build"
echo "3. Проверьте отчет: PROJECT_ERROR_ANALYSIS_REPORT.md"
echo ""
echo "⚠️  Примечание: Некоторые ошибки требуют ручного исправления:"
echo "- Миграция с ExoPlayer на Media3"
echo "- Исправление неиспользуемых параметров"
echo "- Обновление устаревших API"