name: Ktlint Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint && chmod +x ktlint
      - name: Run ktlint
        run: |
          ./ktlint "app/src/main/java/com/example/mrcomic/**/*.kt"
      - name: Run ktlint and generate report
        run: |
          ./ktlint --reporter=checkstyle,output=ktlint-report.xml "app/src/main/java/com/example/mrcomic/**/*.kt"
      - name: Upload Ktlint report
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: ktlint-report.xml

  ktlint-autofix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint && chmod +x ktlint
      - name: Run ktlint with auto-fix
        run: |
          ./ktlint -F "app/src/main/java/com/example/mrcomic/**/*.kt" 